//
// readregisters.c
//
// DO NOT EDIT THIS FILE.  This file was generated automatically
// by a script that converts an assembler listing into a C structure
// containing the hex values of the instructions in the listing.
// You must edit the assembler source directly and execute the build
// again.
//

unsigned int aui_readregisters_code[] =
tgt_compile(\
".set noat\n" \
"1:mtc0 t7,c0_desave;\n" \
"lui t7,0xff20;\n" \
"sw zero,0x1f8(t7);\n" \
"sw at,0x1f8(t7);\n" \
"mfc0 t7,c0_desave;\n" \
"mtc0 at,c0_desave;\n" \
"lui at,0xff20;\n" \
"sw v0,0x1f8(at);\n" \
"sw v1,0x1f8(at);\n" \
"sw a0,0x1f8(at);\n" \
"sw a1,0x1f8(at);\n" \
"sw a2,0x1f8(at);\n" \
"sw a3,0x1f8(at);\n" \
"sw t0,0x1f8(at);\n" \
"sw t1,0x1f8(at);\n" \
"sw t2,0x1f8(at);\n" \
"sw t3,0x1f8(at);\n" \
"sw t4,0x1f8(at);\n" \
"sw t5,0x1f8(at);\n" \
"sw t6,0x1f8(at);\n" \
"sw t7,0x1f8(at);\n" \
"sw s0,0x1f8(at);\n" \
"sw s1,0x1f8(at);\n" \
"sw s2,0x1f8(at);\n" \
"sw s3,0x1f8(at);\n" \
"sw s4,0x1f8(at);\n" \
"sw s5,0x1f8(at);\n" \
"sw s6,0x1f8(at);\n" \
"sw s7,0x1f8(at);\n" \
"sw t8,0x1f8(at);\n" \
"sw t9,0x1f8(at);\n" \
"sw k0,0x1f8(at);\n" \
"sw k1,0x1f8(at);\n" \
"sw gp,0x1f8(at);\n" \
"sw sp,0x1f8(at);\n" \
"sw s8,0x1f8(at);\n" \
"sw ra,0x1f8(at);\n" \
"sw v0,0x1fc(at);\n" \
"mfc0 v0,c0_status;\n" \
"sw v0,0x1f8(at);\n" \
"mflo v0;\n" \
"sw v0,0x1f8(at);\n" \
"mfhi v0;\n" \
"sw v0,0x1f8(at);\n" \
"mfc0 v0,c0_badvaddr;\n" \
"sw v0,0x1f8(at);\n" \
"mfc0 v0,c0_cause;\n" \
"sw v0,0x1f8(at);\n" \
"mfc0 v0,c0_depc;\n" \
"sw v0,0x1f8(at);\n" \
"lui at,0xff20;\n" \
"lw v0,0x1fc(at);\n" \
"mfc0 at,c0_desave;\n" \
"b 1b;\n" \
"nop ;\n" \
);

